const getPath = path => {
  return require(`@/assets/imgs/useragent/${path}`)
}

const browser = {
  'Arora': getPath('arora.svg'),
  'Avant': getPath('avant.svg'),
  '2345Explorer': getPath('2345Explorer.svg'),
  'Chrome': getPath('chrome.svg'),
  'Chrome Headless': getPath('chrome.svg'),
  'Chrome WebView': getPath('chrome.svg'),
  'Chromium': getPath('chromium.svg'),
  'Firefox': getPath('firefox.svg'),
  'Fennec': getPath('firefox.svg'),
  'IE': getPath('ie.svg'),
  'IEMobile': getPath('ie.svg'),
  'Edge': getPath('edge.svg'),
  'Opera': getPath('opera.svg'),
  'Opera Mini': getPath('opera.svg'),
  'Opera Mobi': getPath('opera.svg'),
  'Safari': getPath('safari.svg'),
  'Mobile Safari': getPath('safari.svg'),
  'UCBrowser': getPath('uc.svg'),
  'Vivaldi': getPath('vivaldi.svg'),
  'WeChat': getPath('wechat.svg'),
  'Yandex': getPath('yandex.svg'),
  'QQBrowser': getPath('QQBrowser.svg'),
  'QQBrowserLite': getPath('QQBrowser.svg'),
  'BIDUBrowser': getPath('baidu.svg'),
  'Baidu': getPath('baidu.svg'),
  'Basilisk': getPath('basilisk.svg'),
  'Camino': getPath('camino.svg'),
  'Comodo Dragon': getPath('comodo-dragon.svg'),
  'Epiphany': getPath('epiphany.svg'),
  'Facebook': getPath('facebook.svg'),
  'Falkon': getPath('falkon.svg'),
  'Firebird': getPath('firebird.svg'),
  'GoBrowser': getPath('GOBrowser.svg'),
  'ICE Browser': getPath('ICEBrowser.svg'),
  'IceDragon': getPath('ICEBrowser.svg'),
  'IceCat': getPath('IceCat.svg'),
  'Iceweasel': getPath('Iceweasel.svg'),
  'K-Meleon': getPath('K-Meleon.svg'),
  'Lunascape': getPath('lunascape.svg'),
  'Maxthon': getPath('maxthon.svg'),
  'Puffin': getPath('puffin.svg'),
  'Quark': getPath('quark.svg'),
  'QupZilla': getPath('qupZilla.svg'),
  'SeaMonkey': getPath('seaMonkey.svg'),
  'Sleipnir': getPath('sleipnir.svg'),
  'Waterfox': getPath('waterfox.svg'),
  'default': getPath('browser.svg')
}

const os = {
  'Windows_10': getPath('windows_win10.svg'),
  'Windows_8': getPath('windows_win8.svg'),
  'Windows_7': getPath('windows_win7.svg'),
  'Windows_XP': getPath('windows_winXP.svg'),
  'Android': getPath('android.svg'),
  'Arch': getPath('arch.svg'),
  'CentOS': getPath('centOS.svg'),
  'Fedora': getPath('fedora.svg'),
  'Firefox OS': getPath('firefox.svg'),
  'FreeBSD': getPath('freeBSD.svg'),
  'Debian': getPath('debian.svg'),
  'Fuchsia': getPath('fuchsia.svg'),
  'Gentoo': getPath('gentoo.svg'),
  'iOS': getPath('iOS.svg'),
  'Linux': getPath('linux.svg'),
  'Mac OS': getPath('iphone.svg'),
  'Mageia': getPath('mageia.svg'),
  'GNU': getPath('GNU.svg'),
  'default': getPath('system.svg')
}

export { browser, os }
